src/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView,RegisterView
from .views import home_page,contact_page,about_page
from accounts.views import guest_register_page
from addresses.views import check_out_address_create_view,check_out_address_reuse_view
from carts.views import cart_detail_api_view
from billing.views import payment_method_view, payment_method_createview
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

urlpatterns = [

    url(r'^bootstrap/$',TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^search/',include('search.urls',namespace='search')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^carts/',include('carts.urls',namespace='carts')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^billing/payment_method/$',payment_method_view,name='billing_payment_method'),
    url(r'^billing/payment_method/create/$',payment_method_createview,name='billing_payment_method_endpoint'),
    url(r'^check_out/address/reuse_view/$',check_out_address_reuse_view,name='check_out_address_reuse'),
    url(r'^check_out/address/create_view/$',check_out_address_create_view,name='check_out_address_create_view'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^api/cart/$',cart_detail_api_view,name='cart-api'),
    url(r'^register/guest/$',guest_register_page,name='guest_register'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^login/$',LoginView.as_view(),name='login'),
	url(r'^contact/$',contact_page,name='contact'),
	url(r'^about/$',about_page,name='about'),
	url(r'^$',home_page,name='home'),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns=urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns=urlpatterns+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/carts/urls.py
from django.conf.urls import url
from .views import (cart_home,
                    cart_update,check_out,check_out_complete_view)
app_name='carts'
urlpatterns = [
    url(r'^success/$',check_out_complete_view,name='success'),
    url(r'^check_out/$',check_out,name='checkout'),
    url(r'^update/$',cart_update,name='update'),
    url(r'^$',cart_home,name='home'),
]

src/products/urls.py
from django.conf.urls import url
from products.views import (ProductListView,
                            ProductDetailSlugView,)
app_name='products'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(),name='detail'),
    url(r'^$',ProductListView.as_view(),name='list'),

]

src/carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save,post_save,m2m_changed
from decimal import Decimal
# Create your models here.
User=settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def get_or_new(self,request):
        cart_id=request.session.get('cart_id',None)
        qs=self.get_queryset().filter(id=cart_id)
        if qs.count()==1:
            obj_new=False
            print('Cart Exists')
            print(cart_id)
            cart_obj=qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user=request.user
                cart_obj.save()
        else:
            obj_new=True
            cart_obj=Cart.objects.new(user=request.user)
            request.session['cart_id']=cart_obj.id
        return cart_obj, obj_new

    def new(self,user=None):
        print(user)
        user_obj=None
        if user is not None:
            if user.is_authenticated():
                user_obj=user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user=models.ForeignKey(User,null=True,blank=True)
    products=models.ManyToManyField(Product, blank=True)
    subtotal=models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    total=models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    objects=CartManager()
    def __str__(self):
        return str(self.id)

# This function is called whenever we changed the products in the cart. And
# returns the final price of all producs present in carts

def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action=='post_add' or action=='post_remove' or action=='post_clear':
        products=instance.products.all()
        total=0
        for product in products:
            total+=product.price
        if instance.subtotal!=total:
            instance.subtotal=total
            instance.save()

# Signals
m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)


def pre_save_cart_receiver(sender,instance,*args,**kwargs):
    if instance.subtotal>0:
        instance.total=Decimal(instance.subtotal) + Decimal(10)
    else:
        instance.total=0

pre_save.connect(pre_save_cart_receiver,sender=Cart)

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<!-- Stripe CSS -->
<link rel="stylesheet" href="{% static 'css/stripe_custom_file.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{%static 'css/main.css'%}">
<!-- <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> -->
<!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-zFzXNZnkXgOSk/hRVQNKFU1ZqC9h18Ge1sp4XCwupvrh3zLMRHclbusmMKTznUnX" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

src/templates/base/forms.html
{% extends 'base.html' %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method="POST" action="{% if action_url %} {{action_url}} {% endif %}">
  {%csrf_token%}
  {% if next_url %}
  <input type="hidden" name="next" value="{{next_url}}"/>
  {% endif %}
  {{form.as_p}}<br>
  <button class="btn btn-primary" type="submit">Save</button>
</form>
</div>
{% endblock %}

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>
<!-- Custom JavaScript -->
<script src="{% static 'js/custom_ecommerce.js' %}"></script>
<!-- Ecommerce stripe Integration JavaScript -->
<script src="{% static 'js/ecommerce.main.js' %}"></script>
<!-- Django AJAX CSRF Token -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- JS Rendering -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js"></script>

{% include 'base/jstemplates.html' %}

src/templates/base/jstemplates.html
{% verbatim %}
<!-- Minifying using JAvascript render to Make it Reusable -->
<script id='stripeTemplate' type="text/x-jsrender">
  <form class="payment-form" action="/charge" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
    <div class="form-row">
      <!-- <label for="card-element">
        Credit or debit card
      </label> -->
      <div id="card-element" class="form-control">
        <!-- A Stripe Element will be inserted here. -->
      </div>

      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>
    <br>
    <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
  </form>
</script>
{% endverbatim %}

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'carts:home' as carts_url %}

<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark mb-3">
  <a class="navbar-brand" href="{{home_url}}"> <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">{% if brand_name %} {{brand_name}} {% else %} Ecommerce {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{contact_url}}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
        <a class="nav-link" href="{{products_list_url}}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{logout_url}}">Signoff</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{register_url}}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{login_url}}">Signin</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == carts_url %}active{% endif %}">
        <a class="nav-link" href="{{carts_url}}"><span class="navbar-count">{{request.session.cart_list}}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
       <!-- <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown Menu
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div> -->
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>